"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Velociraptor.py']
APP_NAME = 'Velociraptor'
DATA_FILES = []
OPTIONS = {
        'argv_emulation': True,
        'matplotlib_backends': '-',
        'iconfile': 'velociraptor.icns',
        'plist': {
            'CFBundleName': APP_NAME,
            'CFBundleDisplayName': APP_NAME,
            'CFBundleGetInfoString': "Manage bike rides",
            'CFBundleIdentifier': "com.loicseguin.velociraptor",
            'CFBundleVersion': "0.1.0",
            'CFBundleShortVersionString': "0.1.0",
            'NSHumanReadableCopyright': "Copyright © 2017, Loïc Séguin-Charbonneau, All Rights Reserved",
            # 'PyRuntimeLocations': [
                # '@executable_path/../Frameworks/libpython3.6m.dylib',
                # '/Users/loic/miniconda3/lib/libpython3.6m.dylib'
               # ],
            },
         'excludes': ['qt5']
        }

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

